# Generated by Django 4.2.5 on 2023-09-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_price_product_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
